services:
  app:
    build: .
    container_name: chat_app_be
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules # tránh ghi đè thư mục node_modules trong container
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - mongodb
      - redis
    networks:
      - chat_network

  mongodb:
    image: mongo:7.0
    container_name: chat_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - chat_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: chat_mongo_express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - chat_network

  redis:
    image: redis:7.2.4
    container_name: chat_redis_chat
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - '6379:6379'
    command: [ 'redis-server', '--requirepass', 'admin', '--appendonly', 'no' ]
    networks:
      - chat_network

volumes:
  mongo_data:
  redis_data:
networks:
  chat_network:
    driver: bridge
